# Use postgres/example user/password credentials
version: '3.1'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: secret

    pgadmin
        image: dpage/pgadmin4
        restart: always
        ports:
            - 80:5050
        environment:
            PGADMIN_DEFAULT_PASSWORD: password
