# Use postgres/example user/password credentials
version: '2.1'

services:

    postgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        networks:
            - kong
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - /tmp/postgres:/var/lib/postgresql/data

    pgadmin:
        image: fenglc/pgadmin4
        restart: always
        ports:
            - 5050:5050
        networks:
            - kong
        links:
            - postgres:postgres

        #login: pgadmin4@pgadmin.org
        #password: admin

    # gateway:
    #     image: kong:latest
    #     container_name: kong
    #     restart: always
    #     ports:
    #       - "8000:8000"
    #       - "8443:8443"
    #       - "8001:8001"
    #       - "7946:7946"
    #       - "7946:7946/udp"
    #     environment:
    #       - KONG_NGINX_DAEMON=off
    #       - KONG_DATABASE=postgres
    #       - KONG_PG_HOST=postgres
    #       - KONG_PG_USER=kong
    #       - KONG_PG_PASSWORD=secret
    #     links:
    #       - postgres:postgres
    #     networks:
    #       - kong
    #     depends_on:
    #       migration:
    #         condition: service_started
    #     volumes:
    #       - ../../../.luarocks/share/lua:/usr/local/share/lua
    #       - ../../../.luarocks/lib:/usr/local/lib

    migration:
        image: kong
        environment:
          - KONG_DATABASE=postgres
          - KONG_PG_HOST=postgres
          - KONG_PG_USER=kong
          - KONG_PG_PASSWORD=secret
        command: kong migrations up
        networks:
          - kong
        links:
          - postgres:postgres
        volumes:
          - ../../../.luarocks/share/lua:/usr/local/share/lua
          - ../../../.luarocks/lib:/usr/local/lib

    ui:
        image: pantsel/konga
        container_name: kong-dashboard
        dns:
          - 127.0.0.1
        ports:
          - "1337:1337"
        environment:
          - DB_ADAPTER=postgres
          - DB_HOST=postgres
          - DB_USER=konga
          - DB_PASSWORD=secret
          - DB_DATABASE=konga
        networks: 
          - kong
        links:
          - postgres:postgres
          #- gateway:kong

networks:
   kong:
      driver: bridge 
